# Generated by Django 3.0.6 on 2020-05-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=250, unique=True)),
            ],
        ),
    ]
